### ISSUE TITLE
Google Play Games REST services

### ISSUE THREAD

**Issue by ramsestom** [SempaiGames/extension-multigames#3]
Correct me if I am wrong but, as I understand, the extension-multigames integrates the extension-gpgrest for Google Play Games REST services, wich should be work on all plateforms.
I do not clearly understood how the extension would work if I only use this Google Play Games REST API though. For example, if I request a Multigames.displayAchievements() or a  Multigames.displayLeaderboard("leaderboard_completed_levels") what would the achievment or leaderboard look like? Because unlike traditional Google Play Games API (only available on android with your extension), there is no google built-in layout to display the result of the rest query on every platform. So did you create a default leaderboard and achievments window yourself, that would work on every platform or is it something else?
Also, what is used to authenticate the player with the REST API. Would a playerID be the same as if I used Google Play Games native API (and if so, can I switch from one method to the other on android and keep my player scores and achievments recorded with native GPG API if I switch to use GPG REST API) or is it something entirely different?

**Comment by fbricker** [comment]
Hi, this extension uses extension-gpgrest extension when needed. Extension mutigames is intended to provide a unique API for managing many other gaming extensions.

So, if you use Google Play Games targeting Android, it'll use extension-google-play-games (native extension). But on other platforms, it'll use extension-gpgrest (https://github.com/SempaiGames/extension-gpgrest)

Said that, you can take a look at how extension-gpgrest implements the displayLeaderboard (but basically, it uses rest services to get information and generates a custom UI using StablexUI that looks quite similar to the official google play games native API on android).

For authentication, it calls native browser login and uses the rest-api token exchange (which stores using OpenFL's SharedObject)

Thanks!
Federico

**Comment by ramsestom** [comment]
Thanks for the reply. Not sure I completely understood though. Can I use the google play service REST api on every platform (even on android) or am I forced to use the google play service android native api on android? And if so, would the leaderbords be shared between different platforms (like a flash version of my game and an android one)?

**Comment by fbricker** [comment]
Hi, yes... you can use the REST for every platform. But I recommend you to use the native for android and REST for the other platforms, since native provides you better user experience.

Anyway: If you use extension-multigames, you don't need to change how you integrate native and rest (as the extension will use native on android and rest on blackberry, windows, mac, flash, etc).

About sharing leaderboard: Yes... your leaderboards will be shared among different platforms :+1: 

About flash: I'm not sure if the REST version will work properly on flash (we never tested on flash... it may work, but it may need some adjustments).

**Comment by ramsestom** [comment]
I tested it on flash and actually this doesn't work:
C:/HaxeToolkit/haxe/lib/extension-gpgrest/1,0,1/Source/com/sempaigames/gplayrest/Auth.hx:90: characters 2-8 : Unknown identifier : Thread
C:/HaxeToolkit/haxe/lib/extension-gpgrest/1,0,1/Source/com/sempaigames/gplayrest/Auth.hx:91: characters 11-31 : You cannot access the sys package while targeting flash (for sys.net.Socket)

Not a real issue for me though as I am just using flash for development (it compiles almost immediately unlike android or cpp targets) but my final targets would be mobile targets (android, ios, blackberry and html5 for windows mobile or firefoxOS)

**Comment by fbricker** [comment]
I see... we need to change some stuff to make this work on flash. 
But considering that flash is on it's way out, I think we should focus more on the HTML5 output for now.

Anyway, ww'll try to do this if we have some free time.

Thanks for the feedback!
Federico

**Comment by ramsestom** [comment]
In fact, in flash I don't understand why I have these errors. I would like the extension to have no effect for now on flash but not to throw any compilation error. I just don't understand why lime is trying to compile com/sempaigames/gplayrest classes when targeting flash as gplayrest classes are supposed to be called only with the gpgrest compilation flag (every gplayrest call in Multigames.hx is inside a #if gpgrest block)...

**Comment by fbricker** [comment]
Is it possible that you're defining / setting the gpgrest var yourself?

Can you post your project.xml (and in case you modified the extension, the include.xml)?
