### ISSUE TITLE
compilation issues with gpgrest

### ISSUE THREAD

**Issue by ramsestom** [SempaiGames/extension-multigames#4]
I tried to compile a project with the command line:
 lime test windows -Dgpgrest

I use latest lime (2.7.0) and openfl (3.4.0) versions and compile with openfl next mode.
The compilation crashed with these errors: 

C:/HaxeToolkit/haxe/lib/extension-gpgrest/1,0,1/Source/com/sempaigames/gplayrest/ui/BmpD
ataCache.hx:47: characters 14-38 : Class<openfl.display.BitmapData> has no field loadFro
mBytes
C:/HaxeToolkit/haxe/lib/extension-gpgrest/1,0,1/Source/com/sempaigames/gplayrest/ui/UrlB
mp.hx:71: characters 29-53 : Class<openfl.display.BitmapData> has no field loadFromBytes

C:/HaxeToolkit/haxe/lib/extension-gpgrest/1,0,1/Source/com/sempaigames/gplayrest/ui/BmpD
ataCache.hx:60: characters 27-32 : String should be openfl.geom.Rectangle
C:/HaxeToolkit/haxe/lib/extension-gpgrest/1,0,1/Source/com/sempaigames/gplayrest/ui/BmpD
ataCache.hx:60: characters 27-32 : For function argument 'rect'
C:/HaxeToolkit/haxe/lib/extension-gpgrest/1,0,1/Source/com/sempaigames/gplayrest/ui/Prog
ressBmp.hx:94: characters 39-47 : Float should be Null<Int>
C:/HaxeToolkit/haxe/lib/extension-gpgrest/1,0,1/Source/com/sempaigames/gplayrest/ui/Prog
ressBmp.hx:94: characters 39-47 : Float should be Int
C:/HaxeToolkit/haxe/lib/extension-gpgrest/1,0,1/Source/com/sempaigames/gplayrest/ui/Prog
ressBmp.hx:94: characters 39-47 : For optional function argument 'size'

**Comment by fbricker** [comment]
Hi, I think this is due to an incompatibility between gpgrest and lime NEXT. Please move this issue to gpgrest repository, so we can address it there when we have some time :)

Also, if you can check if this compiles right using -Dlegacy, and tell this in the ticket, it'll be great!

Thanks!

**Comment by ramsestom** [comment]
Yes. with openfl legacy it compiles fine. Would open the issue on the gpgrest repository.

**Comment by fbricker** [comment]
:+1:
