### ISSUE TITLE
Issues with GooglePlay services

### ISSUE THREAD

**Issue by ghost** [SempaiGames/extension-multigames#7]
Hi,
I have built my project and many parts of it work, however some of the implementation is not entirely clear, and things like achievements do not work properly.
It seems that I can connect initially to the Google Play services but subsequent tries do not allow a connection.
And as well, 

```
Multigames.setProgress(myAcheivement,currentNumber,totalNumber);
```

does not seem to work correctly.
There are some things that are a bit unclear on how to implement them in your documentation, but I am new to haXe and GooglePlay services, so I may be missing something simple.
I did indeed follow your example.
There are a few things I am unable to fully parse in my mind, for example:

```
Multigames.initGPGRest('XXXXXXXX-XXXXXXXXX.apps.googleusercontent.com','XXXXXXXXXXXXXXXXXX');
```

The first url portion straight forward, however the 'client secret' is not documented very well here (and in the other files).  So I am not sure exactly how to proceed with it.

Again, I am very new to the language haXe, so I may be missing something very simple and obvious.
I did include this in my Project.xml (I'm using haxeflixel as well if that matters)

```
    <setenv name="GOOGLE_PLAY_GAMES_ID" value="numberRemovedForObiviousReasons" />
    <haxelib name="extension-multigames" />
    <haxelib name="extension-googleplaygames" if="android" />
    <haxelib name="extension-gpgrest" unless="android" />
```

If I can get a clear understanding on this I would not mind adding a Wiki page to explain this in detail to others who may face the same things as myself

**Comment by fbricker** [comment]
Hi, we've improved the main documentation (https://github.com/SempaiGames/extension-multigames)
I hope this helps 👍 

Thanks for your contribution.
